(function(){var b,f=C.$;b=C.klass({extend:C.Event,prop:{createjssrc:"a",srccreatestart:"b",srcloaded:"c"}});b={observer:new C.Observer,e:new b,el:new function(){return{check_all:f("#all"),btn_create:f("#create"),srcs:f("#srcfile li input"),srcarea:f("#srcarea")}},dependency:new function(){return{active:{selector_methods:["selector"],selector_methods_animate:["selector","selector_methods","Tweener","Animation"],ExternalInterface:["HashQuery","ExternalInterface_Android","ExternalInterface_IOS"],ExternalInterface_Android:["HashQuery",
"ExternalInterface"],ExternalInterface_IOS:["HashQuery","ExternalInterface"],Audio:["Embed"],Sound:["Embed","Media","Audio"],Video:["Embed"],Movie:["Embed","Media","Video"],Modal:["Scroll"],Media:["Embed","Audio","Video"],LocalStorage:["WebStorage"],SessionStorage:["WebStorage"],DeviceMotion:["DeviceAction"],DeviceOrientation:["DeviceAction"],DeviceShake:["DeviceAction","DeviceMotion","DeviceOrientation"],View:["selector","selector_methods"],Model:["selector","DataStore","Observer"]},passive:{selector:["selector_methods",
"selector_methods_animate","View"],selector_methods:["selector_methods_animate","View"],DataStore:["Model"],Observer:["Model"],HashQuery:["ExternalInterface","ExternalInterface_Android","ExternalInterface_IOS"],ExternalInterface:["ExternalInterface_Android","ExternalInterface_IOS"],Tweener:["selector_methods_animate"],Embed:["Audio","Video","Media","Sound","Movie"],Media:["Audio","Video","Sound","Movie"],Scroll:["Modal"],Audio:["Sound"],Video:["Movie"],WebStorage:["LocalStorage","SessionStorage"],
DeviceAction:["DeviceMotion","DeviceOrientation","DeviceShake"],DeviceMotion:["DeviceShake"],DeviceOrientation:["DeviceShake"]},waste:{ExternalInterface:["ExternalInterface_Android","ExternalInterface_IOS"],Media:["Audio","Video","Sound","Movie"],DeviceAction:["DeviceMotion","DeviceOrientation","DeviceShake"]}}},ajax:new function(){return{jssrc:function(a){(new C.Ajax).request({url:a.src+"?update="+Date.now(),callback:function(c){a.result[a.src]=c;a.callback()}})},closurecompiler:function(a){var c=
new C.Ajax,g="",g="compilation_level=ADVANCED_OPTIMIZATIONS&output_format=text&output_info=compiled_code&&js_code="+a.src;c.request({url:"http://closure-compiler.appspot.com/compile",type:"POST",query:g,callback:function(c){a.callback(c)}})}}}};b.makeSrc=new function(a){var c=a.e,g=a.observer,b=a.ajax,d=a.el,e={make:function(a){for(var e="",h=0,l=d.srcs.length,m,j="/* optimize: ";h<l;h++)m=d.srcs[h].value,a[m]&&(f(d.srcs[h]).parent()[0].querySelector(".name")&&(j+=f(d.srcs[h]).parent()[0].querySelector(".name").innerHTML+
" "),j+="",e+=encodeURIComponent(a[m]));j+="*/\n";b.closurecompiler({src:e,callback:function(d){g.fire(c.createjssrc,a["src/clouser_start.js"]+j+d+a["src/clouser_end.js"])}});return e}};g.on(c.srcloaded,function(a){e.make(a)});return e}(b);b.btnCreate=new function(a){var c=a.e,g=a.observer,b=a.ajax,d=a.el,e={requestJS:function(){var a=0,f=0,h=d.srcs.length,l={},m=function(){f--;0===f&&g.fire(c.srcloaded,l)};g.fire(c.srccreatestart,l);for(e.unbind();a<h;a++)d.srcs[a].checked&&(f++,b.jssrc({src:d.srcs[a].value,
result:l,callback:m}))},unbind:function(){d.btn_create.attr("value","request...");return d.btn_create.off(C.e.CLICK,e.requestJS)},bind:function(){d.btn_create.attr("value","Create.");return d.btn_create.on(C.e.CLICK,e.requestJS)}};e.bind();g.on(c.createjssrc,function(){e.bind()});return e}(b);b.chkAll=new function(a){var c=a.el;a={toggle:function(){var a=0,b=c.srcs.length,d="checked";for(c.check_all[0].checked||(d="");a<b;a++)c.srcs[a].disabled||(c.srcs[a].checked=d)}};c.check_all.on(C.e.CLICK,a.toggle);
return a}(b);b.chkSrc=new function(a){var c=a.dependency,b,k={checkDependency:function(){var a=f(this).parent().parent(),e="passive",p=c.waste,n;this.checked&&(e="active");(b=c[e][a[0].id])&&k.setDependency(b,this.checked);if(!this.checked)for(n in p){e=!0;for(a=p[n].length;a--;)if(f("#"+p[n][a]+" input")[0].checked){e=!1;break}e&&(f("#"+n+" input")[0].checked=!1)}},setDependency:function(a,c){for(var b=0,g=a.length;b<g;b++)f("#"+a[b]+" input")[0].checked=c}};a.el.srcs.on(a.e.CHANGE,k.checkDependency);
return k}(b);b.srcArea=new function(a){var b=a.e,f=a.observer,k=a.el,d={setValue:function(a){k.srcarea[0].value=a},loading:function(){d.setValue("Now Create...")}};f.on(b.createjssrc,d.setValue);f.on(b.srccreatestart,d.loading);return d}(b)})();
